name: 'AWS Marketplace | AWS ECR Login'
inputs:
  aws-role-arn:
    default: "arn:aws:iam::ACCOUNTID:role/GitHubAction-AssumeRoleWithAction"
  aws-region:
    default: "us-east-1"
  aws-marketplace-base-url:
    default: ""
runs:
  using: "composite"
  steps:
    - uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4
      with:
        role-to-assume: ${{ inputs.aws-role-arn }}
        aws-region: ${{ inputs.aws-region }}
    - run: |
        aws ecr get-login-password --region ${{ inputs.aws-region }} | docker login --username AWS --password-stdin ${{ inputs.aws-marketplace-base-url }}/camunda
      shell: bash
