name: "AWS Marketplace | Mirror: Web Modeler"

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: "The image tag for the web-modeler image"
        required: true
        type: string

jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - uses: ./.github/actions/aws-marketplace-ecr-login
        with:
          aws-role-arn: "arn:aws:iam::${{ secrets.DISTRO_CI_AWS_MPLACE_AWS_ACCOUNT_ID }}:role/GitHubAction-AssumeRoleWithAction"
          aws-region: "us-east-1"
          aws-marketplace-base-url: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}

      - name: Docker login to registry.camunda.cloud
        run: docker login --username "$CAMUNDA_REGISTRY_USERNAME" --password "$CAMUNDA_REGISTRY_PASSWORD" registry.camunda.cloud
        env:
          CAMUNDA_REGISTRY_USERNAME: ${{ secrets.DISTRO_CI_DOCKER_USERNAME_CAMUNDA }}
          CAMUNDA_REGISTRY_PASSWORD: ${{ secrets.DISTRO_CI_DOCKER_PASSWORD_CAMUNDA }}
     
      - name: web modeler restapi
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: registry.camunda.cloud/web-modeler-ee/modeler-restapi:${{ inputs.imageTag }}
          to: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}/camunda/camunda8/modeler-restapi:${{ inputs.imageTag }}

      - name: web modeler webapp
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: registry.camunda.cloud/web-modeler-ee/modeler-webapp:${{ inputs.imageTag }}
          to: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}/camunda/camunda8/modeler-webapp:${{ inputs.imageTag }}

      - name: web modeler websockets
        uses: ./.github/actions/aws-marketplace-ecr-mirror
        with:
          from: registry.camunda.cloud/web-modeler-ee/modeler-websockets:${{ inputs.imageTag }}
          to: ${{ secrets.DISTRO_CI_AWS_MPLACE_BASE_URL }}/camunda/camunda8/modeler-websockets:${{ inputs.imageTag }}
